#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tini
Version  : 0.18.0
Release  : 1
URL      : https://github.com/krallin/tini/archive/v0.18.0.tar.gz
Source0  : https://github.com/krallin/tini/archive/v0.18.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: tini-bin = %{version}-%{release}
Requires: tini-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : glibc-staticdev

%description
<!--
#####################################
# THIS FILE IS AUTOGENERATED!       #
#####################################

%package bin
Summary: bin components for the tini package.
Group: Binaries
Requires: tini-license = %{version}-%{release}

%description bin
bin components for the tini package.


%package license
Summary: license components for the tini package.
Group: Default

%description license
license components for the tini package.


%prep
%setup -q -n tini-0.18.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1543254001
mkdir -p clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags} VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1543254001
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/tini
cp LICENSE %{buildroot}/usr/share/package-licenses/tini/LICENSE
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/tini
/usr/bin/tini-static

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/tini/LICENSE
