#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tini
Version  : 0.19.0
Release  : 5
URL      : https://github.com/krallin/tini/archive/v0.19.0/tini-0.19.0.tar.gz
Source0  : https://github.com/krallin/tini/archive/v0.19.0/tini-0.19.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: tini-bin = %{version}-%{release}
Requires: tini-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : glibc-staticdev
Patch1: 0001-Remove-strip-option-to-linker.patch

%description
<!--
#####################################
# THIS FILE IS AUTOGENERATED!       #
#####################################

%package bin
Summary: bin components for the tini package.
Group: Binaries
Requires: tini-license = %{version}-%{release}

%description bin
bin components for the tini package.


%package extras
Summary: extras components for the tini package.
Group: Default

%description extras
extras components for the tini package.


%package license
Summary: license components for the tini package.
Group: Default

%description license
license components for the tini package.


%prep
%setup -q -n tini-0.19.0
cd %{_builddir}/tini-0.19.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1646677471
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1646677471
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/tini
cp %{_builddir}/tini-0.19.0/LICENSE %{buildroot}/usr/share/package-licenses/tini/5d7ef48d42c722ff05c54cb16ca665ca2f97f2c7
pushd clr-build
%make_install
popd
## install_append content
ln -sv /usr/bin/tini-static %{buildroot}/usr/bin/docker-init
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/docker-init
/usr/bin/tini-static

%files extras
%defattr(-,root,root,-)
/usr/bin/tini

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/tini/5d7ef48d42c722ff05c54cb16ca665ca2f97f2c7
